services:
  revx-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: revx-dev-container
    volumes:
      - ~/Dev/revx/:/home/revx/dev:rw
      - ~/.ssh:/home/revx/.ssh:ro
    restart: always
    tty: true
    stdin_open: true
